# -*- coding: utf-8 -*-
"""
/***************************************************************************
 StrictGeoreferencer
                                 A QGIS plugin
 This plugin allows user to georeference any image with the help of reference points.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-26
        copyright            : (C) 2025 by Kolchin S.
        email                : step4in@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load StrictGeoreferencer class from file StrictGeoreferencer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .strict_georeferencer import StrictGeoreferencer
    return StrictGeoreferencer(iface)
